### PR TITLE
Simplify buffer closing logic

### PR DESCRIPTION
**Pull request by hwh33**

### CODE REVIEW

**Comment by hwh33** [comment]
This causes `TestStreamCloseRemoteAfterEcho` to fail, but only because the server now closes too quickly - before the "stop" message is echoed.

**Comment by hwh33** [comment]
[This is where the failure occurs](https://github.com/getlantern/lampshade/blob/harry/issue3336-3/lampshade_test.go#L126).  It kind of seems like that part of the test is just testing the echo server?  Maybe I'm missing something.

**Comment by myleshorton** [comment]
Is this one still relevant @oxtoacart and @hwh33?

**Comment by oxtoacart** [comment]
Nah, IIRC we discussed that the switched to using the closed channel can lead to packets getting lost. Closing PR.

**Pull request closed without merging**
